export const colors = [
  { name: "Red", hex: "#FF0000", tailwind: "bg-red-500" },
  { name: "Green", hex: "#00FF00", tailwind: "bg-green-500" },
  { name: "Blue", hex: "#0000FF", tailwind: "bg-blue-500" },
  { name: "Yellow", hex: "#FFFF00", tailwind: "bg-yellow-500" },
  { name: "Cyan", hex: "#00FFFF", tailwind: "bg-cyan-500" },
  { name: "Orange", hex: "#FFA500", tailwind: "bg-orange-500" },
  { name: "Purple", hex: "#800080", tailwind: "bg-purple-700" },
  { name: "Pink", hex: "#FFC0CB", tailwind: "bg-pink-300" },
  { name: "Lime", hex: "#32CD32", tailwind: "bg-lime-500" },
  { name: "Teal", hex: "#008080", tailwind: "bg-teal-600" },
  { name: "Lavender", hex: "#E6E6FA", tailwind: "bg-purple-200" },
  { name: "Brown", hex: "#A52A2A", tailwind: "bg-amber-700" },
  { name: "Beige", hex: "#F5F5DC", tailwind: "bg-yellow-100" },
  { name: "Maroon", hex: "#800000", tailwind: "bg-red-900" },
  { name: "Mint", hex: "#98FF98", tailwind: "bg-green-200" },
  { name: "Olive", hex: "#808000", tailwind: "bg-yellow-700" },
  { name: "Coral", hex: "#FF7F50", tailwind: "bg-orange-400" },
  { name: "Navy", hex: "#000080", tailwind: "bg-blue-900" },
  { name: "Grey", hex: "#808080", tailwind: "bg-gray-500" },
  { name: "White", hex: "#FFFFFF", tailwind: "bg-white" },
  { name: "Black", hex: "#000000", tailwind: "bg-black" },
  { name: "Crimson", hex: "#DC143C", tailwind: "bg-red-600" },
  { name: "Forest Green", hex: "#228B22", tailwind: "bg-green-700" },
  { name: "Sky Blue", hex: "#87CEEB", tailwind: "bg-sky-300" },
  { name: "Gold", hex: "#FFD700", tailwind: "bg-yellow-400" },
  { name: "Indigo", hex: "#4B0082", tailwind: "bg-indigo-900" },
  { name: "Turquoise", hex: "#40E0D0", tailwind: "bg-teal-300" },
  { name: "Violet", hex: "#EE82EE", tailwind: "bg-violet-400" },
  { name: "Tan", hex: "#D2B48C", tailwind: "bg-yellow-600" },
  { name: "Salmon", hex: "#FA8072", tailwind: "bg-red-300" },
  { name: "Plum", hex: "#DDA0DD", tailwind: "bg-purple-300" },
  { name: "Orchid", hex: "#DA70D6", tailwind: "bg-fuchsia-400" },
  { name: "Khaki", hex: "#F0E68C", tailwind: "bg-yellow-200" },
  { name: "Slate Blue", hex: "#6A5ACD", tailwind: "bg-slate-600" },
  { name: "Periwinkle", hex: "#CCCCFF", tailwind: "bg-indigo-200" },
  { name: "Mauve", hex: "#E0B0FF", tailwind: "bg-purple-300" },
  { name: "Sienna", hex: "#A0522D", tailwind: "bg-amber-700" },
  { name: "Chartreuse", hex: "#7FFF00", tailwind: "bg-lime-400" },
  { name: "Aquamarine", hex: "#7FFFD4", tailwind: "bg-teal-200" },
  { name: "Fuchsia", hex: "#FF00FF", tailwind: "bg-fuchsia-500" },
]

